name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run LInter
      # - name: Run linter
      #   run: bun lint
